//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CuplParser.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Jacobi.CuplLang.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public partial class CuplParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Comments=1, Assembly=2, Company=3, Date=4, Designer=5, Device=6, Format=7, 
		Location=8, Name=9, Partno=10, Revision=11, DeviceName=12, FormatName=13, 
		Pin=14, Append=15, Extension=16, Symbol=17, Number=18, DontCareNumber=19, 
		PrefixHex=20, PrefixOctal=21, PrefixDecimal=22, PrefixBinary=23, Include=24, 
		Define=25, UnDef=26, IfDef=27, IfNotDef=28, EndIf=29, Else=30, Repeat=31, 
		RepEnd=32, Macro=33, MEnd=34, Eq=35, LogicNot=36, LogicAnd=37, LogicOr=38, 
		SemiColon=39, Comma=40, Dot=41, Range=42, BracketOpen=43, BracketClose=44, 
		ParenOpen=45, ParenClose=46, Dollar=47, Quote=48, Underscore=49, WS=50, 
		EndUseSpaces=51, FreeText=52, BinNumber=53, OctNumber=54, HexNumber=55;
	public const int
		RULE_file = 0, RULE_header = 1, RULE_assembly = 2, RULE_company = 3, RULE_date = 4, 
		RULE_designer = 5, RULE_device = 6, RULE_format = 7, RULE_location = 8, 
		RULE_name = 9, RULE_partno = 10, RULE_revision = 11, RULE_freeText = 12, 
		RULE_pin = 13, RULE_pinSingle = 14, RULE_pinList = 15, RULE_pinRange = 16, 
		RULE_numberList = 17, RULE_numberRange = 18, RULE_symbolList = 19, RULE_symbolRange = 20, 
		RULE_equation = 21, RULE_symbol = 22, RULE_expression = 23, RULE_number = 24, 
		RULE_binNumber = 25, RULE_octNumber = 26, RULE_decNumber = 27, RULE_hexNumber = 28, 
		RULE_dontCareNumber = 29, RULE_extension = 30, RULE_binOp = 31, RULE_uniOp = 32;
	public static readonly string[] ruleNames = {
		"file", "header", "assembly", "company", "date", "designer", "device", 
		"format", "location", "name", "partno", "revision", "freeText", "pin", 
		"pinSingle", "pinList", "pinRange", "numberList", "numberRange", "symbolList", 
		"symbolRange", "equation", "symbol", "expression", "number", "binNumber", 
		"octNumber", "decNumber", "hexNumber", "dontCareNumber", "extension", 
		"binOp", "uniOp"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"'INCLUDE'", "'DEFINE'", "'UNDEF'", "'IFDEF'", "'IFNDEF'", "'ENDIF'", 
		"'ELSE'", "'REPEAT'", "'REPEND'", "'MACRO'", "'MEND'", "'='", "'!'", "'&'", 
		"'#'", null, "','", "'.'", "'..'", "'['", "']'", "'('", "')'", "'$'", 
		"'''", "'_'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Comments", "Assembly", "Company", "Date", "Designer", "Device", 
		"Format", "Location", "Name", "Partno", "Revision", "DeviceName", "FormatName", 
		"Pin", "Append", "Extension", "Symbol", "Number", "DontCareNumber", "PrefixHex", 
		"PrefixOctal", "PrefixDecimal", "PrefixBinary", "Include", "Define", "UnDef", 
		"IfDef", "IfNotDef", "EndIf", "Else", "Repeat", "RepEnd", "Macro", "MEnd", 
		"Eq", "LogicNot", "LogicAnd", "LogicOr", "SemiColon", "Comma", "Dot", 
		"Range", "BracketOpen", "BracketClose", "ParenOpen", "ParenClose", "Dollar", 
		"Quote", "Underscore", "WS", "EndUseSpaces", "FreeText", "BinNumber", 
		"OctNumber", "HexNumber"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CuplParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CuplParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CuplParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CuplParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public HeaderContext header() {
			return GetRuleContext<HeaderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(CuplParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PinContext[] pin() {
			return GetRuleContexts<PinContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinContext pin(int i) {
			return GetRuleContext<PinContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EquationContext[] equation() {
			return GetRuleContexts<EquationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EquationContext equation(int i) {
			return GetRuleContext<EquationContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			header();
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Pin) {
				{
				{
				State = 67;
				pin();
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 8864812662784L) != 0)) {
				{
				{
				State = 73;
				equation();
				}
				}
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 79;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeaderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssemblyContext[] assembly() {
			return GetRuleContexts<AssemblyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssemblyContext assembly(int i) {
			return GetRuleContext<AssemblyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompanyContext[] company() {
			return GetRuleContexts<CompanyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompanyContext company(int i) {
			return GetRuleContext<CompanyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DateContext[] date() {
			return GetRuleContexts<DateContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DateContext date(int i) {
			return GetRuleContext<DateContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DesignerContext[] designer() {
			return GetRuleContexts<DesignerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DesignerContext designer(int i) {
			return GetRuleContext<DesignerContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeviceContext[] device() {
			return GetRuleContexts<DeviceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeviceContext device(int i) {
			return GetRuleContext<DeviceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FormatContext[] format() {
			return GetRuleContexts<FormatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FormatContext format(int i) {
			return GetRuleContext<FormatContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext[] location() {
			return GetRuleContexts<LocationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location(int i) {
			return GetRuleContext<LocationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext[] name() {
			return GetRuleContexts<NameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name(int i) {
			return GetRuleContext<NameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PartnoContext[] partno() {
			return GetRuleContexts<PartnoContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PartnoContext partno(int i) {
			return GetRuleContext<PartnoContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RevisionContext[] revision() {
			return GetRuleContexts<RevisionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RevisionContext revision(int i) {
			return GetRuleContext<RevisionContext>(i);
		}
		public HeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHeader(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HeaderContext header() {
		HeaderContext _localctx = new HeaderContext(Context, State);
		EnterRule(_localctx, 2, RULE_header);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4092L) != 0)) {
				{
				State = 91;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Assembly:
					{
					State = 81;
					assembly();
					}
					break;
				case Company:
					{
					State = 82;
					company();
					}
					break;
				case Date:
					{
					State = 83;
					date();
					}
					break;
				case Designer:
					{
					State = 84;
					designer();
					}
					break;
				case Device:
					{
					State = 85;
					device();
					}
					break;
				case Format:
					{
					State = 86;
					format();
					}
					break;
				case Location:
					{
					State = 87;
					location();
					}
					break;
				case Name:
					{
					State = 88;
					name();
					}
					break;
				case Partno:
					{
					State = 89;
					partno();
					}
					break;
				case Revision:
					{
					State = 90;
					revision();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssemblyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assembly() { return GetToken(CuplParser.Assembly, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public AssemblyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assembly; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssembly(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssemblyContext assembly() {
		AssemblyContext _localctx = new AssemblyContext(Context, State);
		EnterRule(_localctx, 4, RULE_assembly);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(Assembly);
			State = 97;
			freeText();
			State = 98;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompanyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Company() { return GetToken(CuplParser.Company, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public CompanyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_company; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompany(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompanyContext company() {
		CompanyContext _localctx = new CompanyContext(Context, State);
		EnterRule(_localctx, 6, RULE_company);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(Company);
			State = 101;
			freeText();
			State = 102;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Date() { return GetToken(CuplParser.Date, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public DateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DateContext date() {
		DateContext _localctx = new DateContext(Context, State);
		EnterRule(_localctx, 8, RULE_date);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(Date);
			State = 105;
			freeText();
			State = 106;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DesignerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Designer() { return GetToken(CuplParser.Designer, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public DesignerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_designer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDesigner(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DesignerContext designer() {
		DesignerContext _localctx = new DesignerContext(Context, State);
		EnterRule(_localctx, 10, RULE_designer);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(Designer);
			State = 109;
			freeText();
			State = 110;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeviceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Device() { return GetToken(CuplParser.Device, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DeviceName() { return GetToken(CuplParser.DeviceName, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		public DeviceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_device; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDevice(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeviceContext device() {
		DeviceContext _localctx = new DeviceContext(Context, State);
		EnterRule(_localctx, 12, RULE_device);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112;
			Match(Device);
			State = 113;
			Match(DeviceName);
			State = 114;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Format() { return GetToken(CuplParser.Format, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FormatName() { return GetToken(CuplParser.FormatName, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		public FormatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_format; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormatContext format() {
		FormatContext _localctx = new FormatContext(Context, State);
		EnterRule(_localctx, 14, RULE_format);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			Match(Format);
			State = 117;
			Match(FormatName);
			State = 118;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Location() { return GetToken(CuplParser.Location, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public LocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LocationContext location() {
		LocationContext _localctx = new LocationContext(Context, State);
		EnterRule(_localctx, 16, RULE_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 120;
			Match(Location);
			State = 121;
			freeText();
			State = 122;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(CuplParser.Name, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 18, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			Match(Name);
			State = 125;
			freeText();
			State = 126;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PartnoContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Partno() { return GetToken(CuplParser.Partno, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public PartnoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_partno; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPartno(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PartnoContext partno() {
		PartnoContext _localctx = new PartnoContext(Context, State);
		EnterRule(_localctx, 20, RULE_partno);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(Partno);
			State = 129;
			freeText();
			State = 130;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RevisionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Revision() { return GetToken(CuplParser.Revision, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public RevisionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_revision; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRevision(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RevisionContext revision() {
		RevisionContext _localctx = new RevisionContext(Context, State);
		EnterRule(_localctx, 22, RULE_revision);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			Match(Revision);
			State = 133;
			freeText();
			State = 134;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FreeTextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] FreeText() { return GetTokens(CuplParser.FreeText); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FreeText(int i) {
			return GetToken(CuplParser.FreeText, i);
		}
		public FreeTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_freeText; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFreeText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FreeTextContext freeText() {
		FreeTextContext _localctx = new FreeTextContext(Context, State);
		EnterRule(_localctx, 24, RULE_freeText);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 136;
				Match(FreeText);
				}
				}
				State = 139;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==FreeText );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PinSingleContext pinSingle() {
			return GetRuleContext<PinSingleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinListContext pinList() {
			return GetRuleContext<PinListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinRangeContext pinRange() {
			return GetRuleContext<PinRangeContext>(0);
		}
		public PinContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pin; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPin(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinContext pin() {
		PinContext _localctx = new PinContext(Context, State);
		EnterRule(_localctx, 26, RULE_pin);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 141;
				pinSingle();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142;
				pinList();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 143;
				pinRange();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinSingleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinSingleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinSingle; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinSingle(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinSingleContext pinSingle() {
		PinSingleContext _localctx = new PinSingleContext(Context, State);
		EnterRule(_localctx, 28, RULE_pinSingle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(Pin);
			State = 147;
			Match(Number);
			State = 148;
			Match(Eq);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 149;
				Match(LogicNot);
				}
			}

			State = 152;
			Match(Symbol);
			State = 153;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumberListContext numberList() {
			return GetRuleContext<NumberListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolListContext symbolList() {
			return GetRuleContext<SymbolListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinListContext pinList() {
		PinListContext _localctx = new PinListContext(Context, State);
		EnterRule(_localctx, 30, RULE_pinList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			Match(Pin);
			State = 156;
			numberList();
			State = 157;
			Match(Eq);
			State = 159;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 158;
				Match(LogicNot);
				}
			}

			State = 161;
			symbolList();
			State = 162;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumberRangeContext numberRange() {
			return GetRuleContext<NumberRangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolRangeContext symbolRange() {
			return GetRuleContext<SymbolRangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinRangeContext pinRange() {
		PinRangeContext _localctx = new PinRangeContext(Context, State);
		EnterRule(_localctx, 32, RULE_pinRange);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 164;
			Match(Pin);
			State = 165;
			numberRange();
			State = 166;
			Match(Eq);
			State = 168;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 167;
				Match(LogicNot);
				}
			}

			State = 170;
			symbolRange();
			State = 171;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(CuplParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(CuplParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(CuplParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(CuplParser.Comma, i);
		}
		public NumberListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberListContext numberList() {
		NumberListContext _localctx = new NumberListContext(Context, State);
		EnterRule(_localctx, 34, RULE_numberList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			Match(BracketOpen);
			State = 174;
			Match(Number);
			State = 179;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 175;
				Match(Comma);
				State = 176;
				Match(Number);
				}
				}
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 182;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(CuplParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(CuplParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Range() { return GetToken(CuplParser.Range, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		public NumberRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberRangeContext numberRange() {
		NumberRangeContext _localctx = new NumberRangeContext(Context, State);
		EnterRule(_localctx, 36, RULE_numberRange);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(BracketOpen);
			State = 185;
			Match(Number);
			State = 186;
			Match(Range);
			State = 187;
			Match(Number);
			State = 188;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Symbol() { return GetTokens(CuplParser.Symbol); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol(int i) {
			return GetToken(CuplParser.Symbol, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(CuplParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(CuplParser.Comma, i);
		}
		public SymbolListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbolList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbolList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolListContext symbolList() {
		SymbolListContext _localctx = new SymbolListContext(Context, State);
		EnterRule(_localctx, 38, RULE_symbolList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			Match(BracketOpen);
			State = 191;
			Match(Symbol);
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 192;
				Match(Comma);
				State = 193;
				Match(Symbol);
				}
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 199;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Range() { return GetToken(CuplParser.Range, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		public SymbolRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbolRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbolRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolRangeContext symbolRange() {
		SymbolRangeContext _localctx = new SymbolRangeContext(Context, State);
		EnterRule(_localctx, 40, RULE_symbolRange);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			Match(BracketOpen);
			State = 202;
			Match(Symbol);
			State = 203;
			Match(Range);
			State = 204;
			Match(Number);
			State = 205;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EquationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SymbolContext symbol() {
			return GetRuleContext<SymbolContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Append() { return GetToken(CuplParser.Append, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExtensionContext extension() {
			return GetRuleContext<ExtensionContext>(0);
		}
		public EquationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEquation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EquationContext equation() {
		EquationContext _localctx = new EquationContext(Context, State);
		EnterRule(_localctx, 42, RULE_equation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Append) {
				{
				State = 207;
				Match(Append);
				}
			}

			State = 211;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 210;
				Match(LogicNot);
				}
			}

			State = 213;
			symbol();
			State = 215;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Dot) {
				{
				State = 214;
				extension();
				}
			}

			State = 217;
			Match(Eq);
			State = 218;
			expression(0);
			State = 219;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolListContext symbolList() {
			return GetRuleContext<SymbolListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SymbolRangeContext symbolRange() {
			return GetRuleContext<SymbolRangeContext>(0);
		}
		public SymbolContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbol; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbol(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolContext symbol() {
		SymbolContext _localctx = new SymbolContext(Context, State);
		EnterRule(_localctx, 44, RULE_symbol);
		try {
			State = 224;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 221;
				Match(Symbol);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 222;
				symbolList();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 223;
				symbolRange();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExpressionUnaryPrefixContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public UniOpContext uniOp() {
			return GetRuleContext<UniOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ExpressionUnaryPrefixContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionUnaryPrefix(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionNumberContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public ExpressionNumberContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionSymbolContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		public ExpressionSymbolContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionSymbol(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionBinaryContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BinOpContext binOp() {
			return GetRuleContext<BinOpContext>(0);
		}
		public ExpressionBinaryContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionBinary(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionPrecedenceContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ParenOpen() { return GetToken(CuplParser.ParenOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ParenClose() { return GetToken(CuplParser.ParenClose, 0); }
		public ExpressionPrecedenceContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionPrecedence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 46;
		EnterRecursionRule(_localctx, 46, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LogicNot:
				{
				_localctx = new ExpressionUnaryPrefixContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 227;
				uniOp();
				State = 228;
				expression(4);
				}
				break;
			case ParenOpen:
				{
				_localctx = new ExpressionPrecedenceContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 230;
				Match(ParenOpen);
				State = 231;
				expression(0);
				State = 232;
				Match(ParenClose);
				}
				break;
			case Symbol:
				{
				_localctx = new ExpressionSymbolContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 234;
				Match(Symbol);
				}
				break;
			case Number:
			case PrefixHex:
			case PrefixOctal:
			case PrefixDecimal:
			case PrefixBinary:
				{
				_localctx = new ExpressionNumberContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 235;
				number();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 244;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExpressionBinaryContext(new ExpressionContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_expression);
					State = 238;
					if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
					State = 239;
					binOp();
					State = 240;
					expression(6);
					}
					} 
				}
				State = 246;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BinNumberContext binNumber() {
			return GetRuleContext<BinNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OctNumberContext octNumber() {
			return GetRuleContext<OctNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DecNumberContext decNumber() {
			return GetRuleContext<DecNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HexNumberContext hexNumber() {
			return GetRuleContext<HexNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DontCareNumberContext dontCareNumber() {
			return GetRuleContext<DontCareNumberContext>(0);
		}
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 48, RULE_number);
		try {
			State = 252;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 247;
				binNumber();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 248;
				octNumber();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 249;
				decNumber();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 250;
				hexNumber();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 251;
				dontCareNumber();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixBinary() { return GetToken(CuplParser.PrefixBinary, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BinNumber() { return GetToken(CuplParser.BinNumber, 0); }
		public BinNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinNumberContext binNumber() {
		BinNumberContext _localctx = new BinNumberContext(Context, State);
		EnterRule(_localctx, 50, RULE_binNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			Match(PrefixBinary);
			State = 255;
			Match(BinNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OctNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixOctal() { return GetToken(CuplParser.PrefixOctal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OctNumber() { return GetToken(CuplParser.OctNumber, 0); }
		public OctNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_octNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOctNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OctNumberContext octNumber() {
		OctNumberContext _localctx = new OctNumberContext(Context, State);
		EnterRule(_localctx, 52, RULE_octNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 257;
			Match(PrefixOctal);
			State = 258;
			Match(OctNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DecNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixDecimal() { return GetToken(CuplParser.PrefixDecimal, 0); }
		public DecNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DecNumberContext decNumber() {
		DecNumberContext _localctx = new DecNumberContext(Context, State);
		EnterRule(_localctx, 54, RULE_decNumber);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 261;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PrefixDecimal) {
				{
				State = 260;
				Match(PrefixDecimal);
				}
			}

			State = 263;
			Match(Number);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HexNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixHex() { return GetToken(CuplParser.PrefixHex, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HexNumber() { return GetToken(CuplParser.HexNumber, 0); }
		public HexNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hexNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHexNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HexNumberContext hexNumber() {
		HexNumberContext _localctx = new HexNumberContext(Context, State);
		EnterRule(_localctx, 56, RULE_hexNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 265;
			Match(PrefixHex);
			State = 266;
			Match(HexNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DontCareNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixBinary() { return GetToken(CuplParser.PrefixBinary, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DontCareNumber() { return GetToken(CuplParser.DontCareNumber, 0); }
		public DontCareNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dontCareNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDontCareNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DontCareNumberContext dontCareNumber() {
		DontCareNumberContext _localctx = new DontCareNumberContext(Context, State);
		EnterRule(_localctx, 58, RULE_dontCareNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			Match(PrefixBinary);
			State = 269;
			Match(DontCareNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtensionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(CuplParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Extension() { return GetToken(CuplParser.Extension, 0); }
		public ExtensionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extension; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExtension(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExtensionContext extension() {
		ExtensionContext _localctx = new ExtensionContext(Context, State);
		EnterRule(_localctx, 60, RULE_extension);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			Match(Dot);
			State = 272;
			Match(Extension);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicAnd() { return GetToken(CuplParser.LogicAnd, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicOr() { return GetToken(CuplParser.LogicOr, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dollar() { return GetToken(CuplParser.Dollar, 0); }
		public BinOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinOpContext binOp() {
		BinOpContext _localctx = new BinOpContext(Context, State);
		EnterRule(_localctx, 62, RULE_binOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 274;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 141149805215744L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UniOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public UniOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_uniOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUniOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UniOpContext uniOp() {
		UniOpContext _localctx = new UniOpContext(Context, State);
		EnterRule(_localctx, 64, RULE_uniOp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 276;
			Match(LogicNot);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 23: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,55,279,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,1,0,1,0,5,0,69,8,0,10,0,12,0,72,
		9,0,1,0,5,0,75,8,0,10,0,12,0,78,9,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,5,1,92,8,1,10,1,12,1,95,9,1,1,2,1,2,1,2,1,2,1,3,1,3,1,3,
		1,3,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,
		8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,
		1,12,4,12,138,8,12,11,12,12,12,139,1,13,1,13,1,13,3,13,145,8,13,1,14,1,
		14,1,14,1,14,3,14,151,8,14,1,14,1,14,1,14,1,15,1,15,1,15,1,15,3,15,160,
		8,15,1,15,1,15,1,15,1,16,1,16,1,16,1,16,3,16,169,8,16,1,16,1,16,1,16,1,
		17,1,17,1,17,1,17,5,17,178,8,17,10,17,12,17,181,9,17,1,17,1,17,1,18,1,
		18,1,18,1,18,1,18,1,18,1,19,1,19,1,19,1,19,5,19,195,8,19,10,19,12,19,198,
		9,19,1,19,1,19,1,20,1,20,1,20,1,20,1,20,1,20,1,21,3,21,209,8,21,1,21,3,
		21,212,8,21,1,21,1,21,3,21,216,8,21,1,21,1,21,1,21,1,21,1,22,1,22,1,22,
		3,22,225,8,22,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,1,23,3,23,237,
		8,23,1,23,1,23,1,23,1,23,5,23,243,8,23,10,23,12,23,246,9,23,1,24,1,24,
		1,24,1,24,1,24,3,24,253,8,24,1,25,1,25,1,25,1,26,1,26,1,26,1,27,3,27,262,
		8,27,1,27,1,27,1,28,1,28,1,28,1,29,1,29,1,29,1,30,1,30,1,30,1,31,1,31,
		1,32,1,32,1,32,0,1,46,33,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,
		34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,0,1,2,0,37,38,47,47,279,
		0,66,1,0,0,0,2,93,1,0,0,0,4,96,1,0,0,0,6,100,1,0,0,0,8,104,1,0,0,0,10,
		108,1,0,0,0,12,112,1,0,0,0,14,116,1,0,0,0,16,120,1,0,0,0,18,124,1,0,0,
		0,20,128,1,0,0,0,22,132,1,0,0,0,24,137,1,0,0,0,26,144,1,0,0,0,28,146,1,
		0,0,0,30,155,1,0,0,0,32,164,1,0,0,0,34,173,1,0,0,0,36,184,1,0,0,0,38,190,
		1,0,0,0,40,201,1,0,0,0,42,208,1,0,0,0,44,224,1,0,0,0,46,236,1,0,0,0,48,
		252,1,0,0,0,50,254,1,0,0,0,52,257,1,0,0,0,54,261,1,0,0,0,56,265,1,0,0,
		0,58,268,1,0,0,0,60,271,1,0,0,0,62,274,1,0,0,0,64,276,1,0,0,0,66,70,3,
		2,1,0,67,69,3,26,13,0,68,67,1,0,0,0,69,72,1,0,0,0,70,68,1,0,0,0,70,71,
		1,0,0,0,71,76,1,0,0,0,72,70,1,0,0,0,73,75,3,42,21,0,74,73,1,0,0,0,75,78,
		1,0,0,0,76,74,1,0,0,0,76,77,1,0,0,0,77,79,1,0,0,0,78,76,1,0,0,0,79,80,
		5,0,0,1,80,1,1,0,0,0,81,92,3,4,2,0,82,92,3,6,3,0,83,92,3,8,4,0,84,92,3,
		10,5,0,85,92,3,12,6,0,86,92,3,14,7,0,87,92,3,16,8,0,88,92,3,18,9,0,89,
		92,3,20,10,0,90,92,3,22,11,0,91,81,1,0,0,0,91,82,1,0,0,0,91,83,1,0,0,0,
		91,84,1,0,0,0,91,85,1,0,0,0,91,86,1,0,0,0,91,87,1,0,0,0,91,88,1,0,0,0,
		91,89,1,0,0,0,91,90,1,0,0,0,92,95,1,0,0,0,93,91,1,0,0,0,93,94,1,0,0,0,
		94,3,1,0,0,0,95,93,1,0,0,0,96,97,5,2,0,0,97,98,3,24,12,0,98,99,5,51,0,
		0,99,5,1,0,0,0,100,101,5,3,0,0,101,102,3,24,12,0,102,103,5,51,0,0,103,
		7,1,0,0,0,104,105,5,4,0,0,105,106,3,24,12,0,106,107,5,51,0,0,107,9,1,0,
		0,0,108,109,5,5,0,0,109,110,3,24,12,0,110,111,5,51,0,0,111,11,1,0,0,0,
		112,113,5,6,0,0,113,114,5,12,0,0,114,115,5,39,0,0,115,13,1,0,0,0,116,117,
		5,7,0,0,117,118,5,13,0,0,118,119,5,39,0,0,119,15,1,0,0,0,120,121,5,8,0,
		0,121,122,3,24,12,0,122,123,5,51,0,0,123,17,1,0,0,0,124,125,5,9,0,0,125,
		126,3,24,12,0,126,127,5,51,0,0,127,19,1,0,0,0,128,129,5,10,0,0,129,130,
		3,24,12,0,130,131,5,51,0,0,131,21,1,0,0,0,132,133,5,11,0,0,133,134,3,24,
		12,0,134,135,5,51,0,0,135,23,1,0,0,0,136,138,5,52,0,0,137,136,1,0,0,0,
		138,139,1,0,0,0,139,137,1,0,0,0,139,140,1,0,0,0,140,25,1,0,0,0,141,145,
		3,28,14,0,142,145,3,30,15,0,143,145,3,32,16,0,144,141,1,0,0,0,144,142,
		1,0,0,0,144,143,1,0,0,0,145,27,1,0,0,0,146,147,5,14,0,0,147,148,5,18,0,
		0,148,150,5,35,0,0,149,151,5,36,0,0,150,149,1,0,0,0,150,151,1,0,0,0,151,
		152,1,0,0,0,152,153,5,17,0,0,153,154,5,39,0,0,154,29,1,0,0,0,155,156,5,
		14,0,0,156,157,3,34,17,0,157,159,5,35,0,0,158,160,5,36,0,0,159,158,1,0,
		0,0,159,160,1,0,0,0,160,161,1,0,0,0,161,162,3,38,19,0,162,163,5,39,0,0,
		163,31,1,0,0,0,164,165,5,14,0,0,165,166,3,36,18,0,166,168,5,35,0,0,167,
		169,5,36,0,0,168,167,1,0,0,0,168,169,1,0,0,0,169,170,1,0,0,0,170,171,3,
		40,20,0,171,172,5,39,0,0,172,33,1,0,0,0,173,174,5,43,0,0,174,179,5,18,
		0,0,175,176,5,40,0,0,176,178,5,18,0,0,177,175,1,0,0,0,178,181,1,0,0,0,
		179,177,1,0,0,0,179,180,1,0,0,0,180,182,1,0,0,0,181,179,1,0,0,0,182,183,
		5,44,0,0,183,35,1,0,0,0,184,185,5,43,0,0,185,186,5,18,0,0,186,187,5,42,
		0,0,187,188,5,18,0,0,188,189,5,44,0,0,189,37,1,0,0,0,190,191,5,43,0,0,
		191,196,5,17,0,0,192,193,5,40,0,0,193,195,5,17,0,0,194,192,1,0,0,0,195,
		198,1,0,0,0,196,194,1,0,0,0,196,197,1,0,0,0,197,199,1,0,0,0,198,196,1,
		0,0,0,199,200,5,44,0,0,200,39,1,0,0,0,201,202,5,43,0,0,202,203,5,17,0,
		0,203,204,5,42,0,0,204,205,5,18,0,0,205,206,5,44,0,0,206,41,1,0,0,0,207,
		209,5,15,0,0,208,207,1,0,0,0,208,209,1,0,0,0,209,211,1,0,0,0,210,212,5,
		36,0,0,211,210,1,0,0,0,211,212,1,0,0,0,212,213,1,0,0,0,213,215,3,44,22,
		0,214,216,3,60,30,0,215,214,1,0,0,0,215,216,1,0,0,0,216,217,1,0,0,0,217,
		218,5,35,0,0,218,219,3,46,23,0,219,220,5,39,0,0,220,43,1,0,0,0,221,225,
		5,17,0,0,222,225,3,38,19,0,223,225,3,40,20,0,224,221,1,0,0,0,224,222,1,
		0,0,0,224,223,1,0,0,0,225,45,1,0,0,0,226,227,6,23,-1,0,227,228,3,64,32,
		0,228,229,3,46,23,4,229,237,1,0,0,0,230,231,5,45,0,0,231,232,3,46,23,0,
		232,233,5,46,0,0,233,237,1,0,0,0,234,237,5,17,0,0,235,237,3,48,24,0,236,
		226,1,0,0,0,236,230,1,0,0,0,236,234,1,0,0,0,236,235,1,0,0,0,237,244,1,
		0,0,0,238,239,10,5,0,0,239,240,3,62,31,0,240,241,3,46,23,6,241,243,1,0,
		0,0,242,238,1,0,0,0,243,246,1,0,0,0,244,242,1,0,0,0,244,245,1,0,0,0,245,
		47,1,0,0,0,246,244,1,0,0,0,247,253,3,50,25,0,248,253,3,52,26,0,249,253,
		3,54,27,0,250,253,3,56,28,0,251,253,3,58,29,0,252,247,1,0,0,0,252,248,
		1,0,0,0,252,249,1,0,0,0,252,250,1,0,0,0,252,251,1,0,0,0,253,49,1,0,0,0,
		254,255,5,23,0,0,255,256,5,53,0,0,256,51,1,0,0,0,257,258,5,21,0,0,258,
		259,5,54,0,0,259,53,1,0,0,0,260,262,5,22,0,0,261,260,1,0,0,0,261,262,1,
		0,0,0,262,263,1,0,0,0,263,264,5,18,0,0,264,55,1,0,0,0,265,266,5,20,0,0,
		266,267,5,55,0,0,267,57,1,0,0,0,268,269,5,23,0,0,269,270,5,19,0,0,270,
		59,1,0,0,0,271,272,5,41,0,0,272,273,5,16,0,0,273,61,1,0,0,0,274,275,7,
		0,0,0,275,63,1,0,0,0,276,277,5,36,0,0,277,65,1,0,0,0,19,70,76,91,93,139,
		144,150,159,168,179,196,208,211,215,224,236,244,252,261
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Jacobi.CuplLang.Parser
