//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CuplParser.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Jacobi.CuplLang.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public partial class CuplParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Comments=1, Assembly=2, Company=3, Date=4, Designer=5, Device=6, Format=7, 
		Location=8, Name=9, Partno=10, Revision=11, Pin=12, Append=13, Extension=14, 
		DeviceName=15, FormatName=16, Symbol=17, Number=18, DontCareNumber=19, 
		PrefixHex=20, PrefixOctal=21, PrefixDecimal=22, PrefixBinary=23, Include=24, 
		Define=25, UnDef=26, IfDef=27, IfNotDef=28, EndIf=29, Else=30, Repeat=31, 
		RepEnd=32, Macro=33, MEnd=34, Eq=35, LogicNot=36, LogicAnd=37, LogicOr=38, 
		SemiColon=39, Comma=40, Dot=41, Range=42, BracketOpen=43, BracketClose=44, 
		ParenOpen=45, ParenClose=46, Dollar=47, Quote=48, WS=49, EndUseSpaces=50, 
		FreeText=51;
	public const int
		RULE_file = 0, RULE_header = 1, RULE_assembly = 2, RULE_company = 3, RULE_date = 4, 
		RULE_designer = 5, RULE_device = 6, RULE_format = 7, RULE_location = 8, 
		RULE_name = 9, RULE_partno = 10, RULE_revision = 11, RULE_freeText = 12, 
		RULE_pin = 13, RULE_pinSimple = 14, RULE_pinList = 15, RULE_pinRange = 16, 
		RULE_numberList = 17, RULE_numberRange = 18, RULE_symbolList = 19, RULE_symbolRange = 20, 
		RULE_equation = 21, RULE_expression = 22, RULE_extension = 23, RULE_binOp = 24, 
		RULE_uniOp = 25;
	public static readonly string[] ruleNames = {
		"file", "header", "assembly", "company", "date", "designer", "device", 
		"format", "location", "name", "partno", "revision", "freeText", "pin", 
		"pinSimple", "pinList", "pinRange", "numberList", "numberRange", "symbolList", 
		"symbolRange", "equation", "expression", "extension", "binOp", "uniOp"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"'INCLUDE'", "'DEFINE'", "'UNDEF'", "'IFDEF'", "'IFNDEF'", "'ENDIF'", 
		"'ELSE'", "'REPEAT'", "'REPEND'", "'MACRO'", "'MEND'", "'='", "'!'", "'&'", 
		"'#'", null, "','", "'.'", "'..'", "'['", "']'", "'('", "')'", "'$'", 
		"'''"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Comments", "Assembly", "Company", "Date", "Designer", "Device", 
		"Format", "Location", "Name", "Partno", "Revision", "Pin", "Append", "Extension", 
		"DeviceName", "FormatName", "Symbol", "Number", "DontCareNumber", "PrefixHex", 
		"PrefixOctal", "PrefixDecimal", "PrefixBinary", "Include", "Define", "UnDef", 
		"IfDef", "IfNotDef", "EndIf", "Else", "Repeat", "RepEnd", "Macro", "MEnd", 
		"Eq", "LogicNot", "LogicAnd", "LogicOr", "SemiColon", "Comma", "Dot", 
		"Range", "BracketOpen", "BracketClose", "ParenOpen", "ParenClose", "Dollar", 
		"Quote", "WS", "EndUseSpaces", "FreeText"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CuplParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CuplParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CuplParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CuplParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public HeaderContext header() {
			return GetRuleContext<HeaderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinContext[] pin() {
			return GetRuleContexts<PinContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinContext pin(int i) {
			return GetRuleContext<PinContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EquationContext[] equation() {
			return GetRuleContexts<EquationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EquationContext equation(int i) {
			return GetRuleContext<EquationContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			header();
			State = 54;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 53;
				pin();
				}
				}
				State = 56;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Pin );
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 58;
				equation();
				}
				}
				State = 61;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 68719616000L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeaderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssemblyContext[] assembly() {
			return GetRuleContexts<AssemblyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssemblyContext assembly(int i) {
			return GetRuleContext<AssemblyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompanyContext[] company() {
			return GetRuleContexts<CompanyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompanyContext company(int i) {
			return GetRuleContext<CompanyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DateContext[] date() {
			return GetRuleContexts<DateContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DateContext date(int i) {
			return GetRuleContext<DateContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DesignerContext[] designer() {
			return GetRuleContexts<DesignerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DesignerContext designer(int i) {
			return GetRuleContext<DesignerContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeviceContext[] device() {
			return GetRuleContexts<DeviceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeviceContext device(int i) {
			return GetRuleContext<DeviceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FormatContext[] format() {
			return GetRuleContexts<FormatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FormatContext format(int i) {
			return GetRuleContext<FormatContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext[] location() {
			return GetRuleContexts<LocationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LocationContext location(int i) {
			return GetRuleContext<LocationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext[] name() {
			return GetRuleContexts<NameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name(int i) {
			return GetRuleContext<NameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PartnoContext[] partno() {
			return GetRuleContexts<PartnoContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PartnoContext partno(int i) {
			return GetRuleContext<PartnoContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RevisionContext[] revision() {
			return GetRuleContexts<RevisionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RevisionContext revision(int i) {
			return GetRuleContext<RevisionContext>(i);
		}
		public HeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHeader(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HeaderContext header() {
		HeaderContext _localctx = new HeaderContext(Context, State);
		EnterRule(_localctx, 2, RULE_header);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4092L) != 0)) {
				{
				State = 73;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Assembly:
					{
					State = 63;
					assembly();
					}
					break;
				case Company:
					{
					State = 64;
					company();
					}
					break;
				case Date:
					{
					State = 65;
					date();
					}
					break;
				case Designer:
					{
					State = 66;
					designer();
					}
					break;
				case Device:
					{
					State = 67;
					device();
					}
					break;
				case Format:
					{
					State = 68;
					format();
					}
					break;
				case Location:
					{
					State = 69;
					location();
					}
					break;
				case Name:
					{
					State = 70;
					name();
					}
					break;
				case Partno:
					{
					State = 71;
					partno();
					}
					break;
				case Revision:
					{
					State = 72;
					revision();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssemblyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assembly() { return GetToken(CuplParser.Assembly, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public AssemblyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assembly; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssembly(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssemblyContext assembly() {
		AssemblyContext _localctx = new AssemblyContext(Context, State);
		EnterRule(_localctx, 4, RULE_assembly);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(Assembly);
			State = 79;
			freeText();
			State = 80;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompanyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Company() { return GetToken(CuplParser.Company, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public CompanyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_company; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompany(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompanyContext company() {
		CompanyContext _localctx = new CompanyContext(Context, State);
		EnterRule(_localctx, 6, RULE_company);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			Match(Company);
			State = 83;
			freeText();
			State = 84;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Date() { return GetToken(CuplParser.Date, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public DateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DateContext date() {
		DateContext _localctx = new DateContext(Context, State);
		EnterRule(_localctx, 8, RULE_date);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(Date);
			State = 87;
			freeText();
			State = 88;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DesignerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Designer() { return GetToken(CuplParser.Designer, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public DesignerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_designer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDesigner(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DesignerContext designer() {
		DesignerContext _localctx = new DesignerContext(Context, State);
		EnterRule(_localctx, 10, RULE_designer);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			Match(Designer);
			State = 91;
			freeText();
			State = 92;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeviceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Device() { return GetToken(CuplParser.Device, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DeviceName() { return GetToken(CuplParser.DeviceName, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		public DeviceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_device; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDevice(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeviceContext device() {
		DeviceContext _localctx = new DeviceContext(Context, State);
		EnterRule(_localctx, 12, RULE_device);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			Match(Device);
			State = 95;
			Match(DeviceName);
			State = 96;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Format() { return GetToken(CuplParser.Format, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FormatName() { return GetToken(CuplParser.FormatName, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		public FormatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_format; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormatContext format() {
		FormatContext _localctx = new FormatContext(Context, State);
		EnterRule(_localctx, 14, RULE_format);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			Match(Format);
			State = 99;
			Match(FormatName);
			State = 100;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Location() { return GetToken(CuplParser.Location, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public LocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_location; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LocationContext location() {
		LocationContext _localctx = new LocationContext(Context, State);
		EnterRule(_localctx, 16, RULE_location);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			Match(Location);
			State = 103;
			freeText();
			State = 104;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(CuplParser.Name, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 18, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(Name);
			State = 107;
			freeText();
			State = 108;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PartnoContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Partno() { return GetToken(CuplParser.Partno, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public PartnoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_partno; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPartno(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PartnoContext partno() {
		PartnoContext _localctx = new PartnoContext(Context, State);
		EnterRule(_localctx, 20, RULE_partno);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			Match(Partno);
			State = 111;
			freeText();
			State = 112;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RevisionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Revision() { return GetToken(CuplParser.Revision, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FreeTextContext freeText() {
			return GetRuleContext<FreeTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndUseSpaces() { return GetToken(CuplParser.EndUseSpaces, 0); }
		public RevisionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_revision; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRevision(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RevisionContext revision() {
		RevisionContext _localctx = new RevisionContext(Context, State);
		EnterRule(_localctx, 22, RULE_revision);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			Match(Revision);
			State = 115;
			freeText();
			State = 116;
			Match(EndUseSpaces);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FreeTextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] FreeText() { return GetTokens(CuplParser.FreeText); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FreeText(int i) {
			return GetToken(CuplParser.FreeText, i);
		}
		public FreeTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_freeText; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFreeText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FreeTextContext freeText() {
		FreeTextContext _localctx = new FreeTextContext(Context, State);
		EnterRule(_localctx, 24, RULE_freeText);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 118;
				Match(FreeText);
				}
				}
				State = 121;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==FreeText );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PinSimpleContext pinSimple() {
			return GetRuleContext<PinSimpleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinListContext pinList() {
			return GetRuleContext<PinListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinRangeContext pinRange() {
			return GetRuleContext<PinRangeContext>(0);
		}
		public PinContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pin; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPin(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinContext pin() {
		PinContext _localctx = new PinContext(Context, State);
		EnterRule(_localctx, 26, RULE_pin);
		try {
			State = 126;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 123;
				pinSimple();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 124;
				pinList();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 125;
				pinRange();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinSimpleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinSimpleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinSimple; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinSimple(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinSimpleContext pinSimple() {
		PinSimpleContext _localctx = new PinSimpleContext(Context, State);
		EnterRule(_localctx, 28, RULE_pinSimple);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(Pin);
			State = 129;
			Match(Number);
			State = 130;
			Match(Eq);
			State = 132;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 131;
				Match(LogicNot);
				}
			}

			State = 134;
			Match(Symbol);
			State = 135;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumberListContext numberList() {
			return GetRuleContext<NumberListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolListContext symbolList() {
			return GetRuleContext<SymbolListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinListContext pinList() {
		PinListContext _localctx = new PinListContext(Context, State);
		EnterRule(_localctx, 30, RULE_pinList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			Match(Pin);
			State = 138;
			numberList();
			State = 139;
			Match(Eq);
			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 140;
				Match(LogicNot);
				}
			}

			State = 143;
			symbolList();
			State = 144;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pin() { return GetToken(CuplParser.Pin, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumberRangeContext numberRange() {
			return GetRuleContext<NumberRangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolRangeContext symbolRange() {
			return GetRuleContext<SymbolRangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public PinRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinRangeContext pinRange() {
		PinRangeContext _localctx = new PinRangeContext(Context, State);
		EnterRule(_localctx, 32, RULE_pinRange);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(Pin);
			State = 147;
			numberRange();
			State = 148;
			Match(Eq);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 149;
				Match(LogicNot);
				}
			}

			State = 152;
			symbolRange();
			State = 153;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(CuplParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(CuplParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(CuplParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(CuplParser.Comma, i);
		}
		public NumberListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberListContext numberList() {
		NumberListContext _localctx = new NumberListContext(Context, State);
		EnterRule(_localctx, 34, RULE_numberList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			Match(BracketOpen);
			State = 156;
			Match(Number);
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 157;
				Match(Comma);
				State = 158;
				Match(Number);
				}
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 164;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(CuplParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(CuplParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Range() { return GetToken(CuplParser.Range, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		public NumberRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberRangeContext numberRange() {
		NumberRangeContext _localctx = new NumberRangeContext(Context, State);
		EnterRule(_localctx, 36, RULE_numberRange);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166;
			Match(BracketOpen);
			State = 167;
			Match(Number);
			State = 168;
			Match(Range);
			State = 169;
			Match(Number);
			State = 170;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Symbol() { return GetTokens(CuplParser.Symbol); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol(int i) {
			return GetToken(CuplParser.Symbol, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(CuplParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(CuplParser.Comma, i);
		}
		public SymbolListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbolList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbolList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolListContext symbolList() {
		SymbolListContext _localctx = new SymbolListContext(Context, State);
		EnterRule(_localctx, 38, RULE_symbolList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			Match(BracketOpen);
			State = 173;
			Match(Symbol);
			State = 178;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 174;
				Match(Comma);
				State = 175;
				Match(Symbol);
				}
				}
				State = 180;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 181;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolRangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketOpen() { return GetToken(CuplParser.BracketOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Range() { return GetToken(CuplParser.Range, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BracketClose() { return GetToken(CuplParser.BracketClose, 0); }
		public SymbolRangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbolRange; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbolRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolRangeContext symbolRange() {
		SymbolRangeContext _localctx = new SymbolRangeContext(Context, State);
		EnterRule(_localctx, 40, RULE_symbolRange);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			Match(BracketOpen);
			State = 184;
			Match(Symbol);
			State = 185;
			Match(Range);
			State = 186;
			Match(Number);
			State = 187;
			Match(BracketClose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EquationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eq() { return GetToken(CuplParser.Eq, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(CuplParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Append() { return GetToken(CuplParser.Append, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExtensionContext extension() {
			return GetRuleContext<ExtensionContext>(0);
		}
		public EquationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEquation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EquationContext equation() {
		EquationContext _localctx = new EquationContext(Context, State);
		EnterRule(_localctx, 42, RULE_equation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Append) {
				{
				State = 189;
				Match(Append);
				}
			}

			State = 193;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LogicNot) {
				{
				State = 192;
				Match(LogicNot);
				}
			}

			State = 195;
			Match(Symbol);
			State = 197;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Dot) {
				{
				State = 196;
				extension();
				}
			}

			State = 199;
			Match(Eq);
			State = 200;
			expression(0);
			State = 201;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExpressionIdentifierContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Symbol() { return GetToken(CuplParser.Symbol, 0); }
		public ExpressionIdentifierContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionUnaryPrefixContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public UniOpContext uniOp() {
			return GetRuleContext<UniOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ExpressionUnaryPrefixContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionUnaryPrefix(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionNumberContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(CuplParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DontCareNumber() { return GetToken(CuplParser.DontCareNumber, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixHex() { return GetToken(CuplParser.PrefixHex, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixBinary() { return GetToken(CuplParser.PrefixBinary, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixDecimal() { return GetToken(CuplParser.PrefixDecimal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PrefixOctal() { return GetToken(CuplParser.PrefixOctal, 0); }
		public ExpressionNumberContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionBinaryContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BinOpContext binOp() {
			return GetRuleContext<BinOpContext>(0);
		}
		public ExpressionBinaryContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionBinary(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExpressionPrecedenceContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ParenOpen() { return GetToken(CuplParser.ParenOpen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ParenClose() { return GetToken(CuplParser.ParenClose, 0); }
		public ExpressionPrecedenceContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionPrecedence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 44;
		EnterRecursionRule(_localctx, 44, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 216;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LogicNot:
				{
				_localctx = new ExpressionUnaryPrefixContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 204;
				uniOp();
				State = 205;
				expression(4);
				}
				break;
			case ParenOpen:
				{
				_localctx = new ExpressionPrecedenceContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 207;
				Match(ParenOpen);
				State = 208;
				expression(0);
				State = 209;
				Match(ParenClose);
				}
				break;
			case Symbol:
				{
				_localctx = new ExpressionIdentifierContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 211;
				Match(Symbol);
				}
				break;
			case Number:
			case DontCareNumber:
			case PrefixHex:
			case PrefixOctal:
			case PrefixDecimal:
			case PrefixBinary:
				{
				_localctx = new ExpressionNumberContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 213;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 15728640L) != 0)) {
					{
					State = 212;
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 15728640L) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 215;
				_la = TokenStream.LA(1);
				if ( !(_la==Number || _la==DontCareNumber) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 224;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExpressionBinaryContext(new ExpressionContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_expression);
					State = 218;
					if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
					State = 219;
					binOp();
					State = 220;
					expression(6);
					}
					} 
				}
				State = 226;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExtensionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(CuplParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Extension() { return GetToken(CuplParser.Extension, 0); }
		public ExtensionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extension; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExtension(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExtensionContext extension() {
		ExtensionContext _localctx = new ExtensionContext(Context, State);
		EnterRule(_localctx, 46, RULE_extension);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			Match(Dot);
			State = 228;
			Match(Extension);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicAnd() { return GetToken(CuplParser.LogicAnd, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicOr() { return GetToken(CuplParser.LogicOr, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dollar() { return GetToken(CuplParser.Dollar, 0); }
		public BinOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinOpContext binOp() {
		BinOpContext _localctx = new BinOpContext(Context, State);
		EnterRule(_localctx, 48, RULE_binOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 141149805215744L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UniOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LogicNot() { return GetToken(CuplParser.LogicNot, 0); }
		public UniOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_uniOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICuplParserVisitor<TResult> typedVisitor = visitor as ICuplParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUniOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UniOpContext uniOp() {
		UniOpContext _localctx = new UniOpContext(Context, State);
		EnterRule(_localctx, 50, RULE_uniOp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232;
			Match(LogicNot);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 22: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,51,235,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,1,0,1,0,4,0,55,8,0,11,0,12,0,56,
		1,0,4,0,60,8,0,11,0,12,0,61,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,
		1,74,8,1,10,1,12,1,77,9,1,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,
		1,4,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,
		9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,1,12,4,12,120,8,
		12,11,12,12,12,121,1,13,1,13,1,13,3,13,127,8,13,1,14,1,14,1,14,1,14,3,
		14,133,8,14,1,14,1,14,1,14,1,15,1,15,1,15,1,15,3,15,142,8,15,1,15,1,15,
		1,15,1,16,1,16,1,16,1,16,3,16,151,8,16,1,16,1,16,1,16,1,17,1,17,1,17,1,
		17,5,17,160,8,17,10,17,12,17,163,9,17,1,17,1,17,1,18,1,18,1,18,1,18,1,
		18,1,18,1,19,1,19,1,19,1,19,5,19,177,8,19,10,19,12,19,180,9,19,1,19,1,
		19,1,20,1,20,1,20,1,20,1,20,1,20,1,21,3,21,191,8,21,1,21,3,21,194,8,21,
		1,21,1,21,3,21,198,8,21,1,21,1,21,1,21,1,21,1,22,1,22,1,22,1,22,1,22,1,
		22,1,22,1,22,1,22,1,22,3,22,214,8,22,1,22,3,22,217,8,22,1,22,1,22,1,22,
		1,22,5,22,223,8,22,10,22,12,22,226,9,22,1,23,1,23,1,23,1,24,1,24,1,25,
		1,25,1,25,0,1,44,26,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,40,42,44,46,48,50,0,3,1,0,20,23,1,0,18,19,2,0,37,38,47,47,236,0,52,
		1,0,0,0,2,75,1,0,0,0,4,78,1,0,0,0,6,82,1,0,0,0,8,86,1,0,0,0,10,90,1,0,
		0,0,12,94,1,0,0,0,14,98,1,0,0,0,16,102,1,0,0,0,18,106,1,0,0,0,20,110,1,
		0,0,0,22,114,1,0,0,0,24,119,1,0,0,0,26,126,1,0,0,0,28,128,1,0,0,0,30,137,
		1,0,0,0,32,146,1,0,0,0,34,155,1,0,0,0,36,166,1,0,0,0,38,172,1,0,0,0,40,
		183,1,0,0,0,42,190,1,0,0,0,44,216,1,0,0,0,46,227,1,0,0,0,48,230,1,0,0,
		0,50,232,1,0,0,0,52,54,3,2,1,0,53,55,3,26,13,0,54,53,1,0,0,0,55,56,1,0,
		0,0,56,54,1,0,0,0,56,57,1,0,0,0,57,59,1,0,0,0,58,60,3,42,21,0,59,58,1,
		0,0,0,60,61,1,0,0,0,61,59,1,0,0,0,61,62,1,0,0,0,62,1,1,0,0,0,63,74,3,4,
		2,0,64,74,3,6,3,0,65,74,3,8,4,0,66,74,3,10,5,0,67,74,3,12,6,0,68,74,3,
		14,7,0,69,74,3,16,8,0,70,74,3,18,9,0,71,74,3,20,10,0,72,74,3,22,11,0,73,
		63,1,0,0,0,73,64,1,0,0,0,73,65,1,0,0,0,73,66,1,0,0,0,73,67,1,0,0,0,73,
		68,1,0,0,0,73,69,1,0,0,0,73,70,1,0,0,0,73,71,1,0,0,0,73,72,1,0,0,0,74,
		77,1,0,0,0,75,73,1,0,0,0,75,76,1,0,0,0,76,3,1,0,0,0,77,75,1,0,0,0,78,79,
		5,2,0,0,79,80,3,24,12,0,80,81,5,50,0,0,81,5,1,0,0,0,82,83,5,3,0,0,83,84,
		3,24,12,0,84,85,5,50,0,0,85,7,1,0,0,0,86,87,5,4,0,0,87,88,3,24,12,0,88,
		89,5,50,0,0,89,9,1,0,0,0,90,91,5,5,0,0,91,92,3,24,12,0,92,93,5,50,0,0,
		93,11,1,0,0,0,94,95,5,6,0,0,95,96,5,15,0,0,96,97,5,39,0,0,97,13,1,0,0,
		0,98,99,5,7,0,0,99,100,5,16,0,0,100,101,5,39,0,0,101,15,1,0,0,0,102,103,
		5,8,0,0,103,104,3,24,12,0,104,105,5,50,0,0,105,17,1,0,0,0,106,107,5,9,
		0,0,107,108,3,24,12,0,108,109,5,50,0,0,109,19,1,0,0,0,110,111,5,10,0,0,
		111,112,3,24,12,0,112,113,5,50,0,0,113,21,1,0,0,0,114,115,5,11,0,0,115,
		116,3,24,12,0,116,117,5,50,0,0,117,23,1,0,0,0,118,120,5,51,0,0,119,118,
		1,0,0,0,120,121,1,0,0,0,121,119,1,0,0,0,121,122,1,0,0,0,122,25,1,0,0,0,
		123,127,3,28,14,0,124,127,3,30,15,0,125,127,3,32,16,0,126,123,1,0,0,0,
		126,124,1,0,0,0,126,125,1,0,0,0,127,27,1,0,0,0,128,129,5,12,0,0,129,130,
		5,18,0,0,130,132,5,35,0,0,131,133,5,36,0,0,132,131,1,0,0,0,132,133,1,0,
		0,0,133,134,1,0,0,0,134,135,5,17,0,0,135,136,5,39,0,0,136,29,1,0,0,0,137,
		138,5,12,0,0,138,139,3,34,17,0,139,141,5,35,0,0,140,142,5,36,0,0,141,140,
		1,0,0,0,141,142,1,0,0,0,142,143,1,0,0,0,143,144,3,38,19,0,144,145,5,39,
		0,0,145,31,1,0,0,0,146,147,5,12,0,0,147,148,3,36,18,0,148,150,5,35,0,0,
		149,151,5,36,0,0,150,149,1,0,0,0,150,151,1,0,0,0,151,152,1,0,0,0,152,153,
		3,40,20,0,153,154,5,39,0,0,154,33,1,0,0,0,155,156,5,43,0,0,156,161,5,18,
		0,0,157,158,5,40,0,0,158,160,5,18,0,0,159,157,1,0,0,0,160,163,1,0,0,0,
		161,159,1,0,0,0,161,162,1,0,0,0,162,164,1,0,0,0,163,161,1,0,0,0,164,165,
		5,44,0,0,165,35,1,0,0,0,166,167,5,43,0,0,167,168,5,18,0,0,168,169,5,42,
		0,0,169,170,5,18,0,0,170,171,5,44,0,0,171,37,1,0,0,0,172,173,5,43,0,0,
		173,178,5,17,0,0,174,175,5,40,0,0,175,177,5,17,0,0,176,174,1,0,0,0,177,
		180,1,0,0,0,178,176,1,0,0,0,178,179,1,0,0,0,179,181,1,0,0,0,180,178,1,
		0,0,0,181,182,5,44,0,0,182,39,1,0,0,0,183,184,5,43,0,0,184,185,5,17,0,
		0,185,186,5,42,0,0,186,187,5,18,0,0,187,188,5,44,0,0,188,41,1,0,0,0,189,
		191,5,13,0,0,190,189,1,0,0,0,190,191,1,0,0,0,191,193,1,0,0,0,192,194,5,
		36,0,0,193,192,1,0,0,0,193,194,1,0,0,0,194,195,1,0,0,0,195,197,5,17,0,
		0,196,198,3,46,23,0,197,196,1,0,0,0,197,198,1,0,0,0,198,199,1,0,0,0,199,
		200,5,35,0,0,200,201,3,44,22,0,201,202,5,39,0,0,202,43,1,0,0,0,203,204,
		6,22,-1,0,204,205,3,50,25,0,205,206,3,44,22,4,206,217,1,0,0,0,207,208,
		5,45,0,0,208,209,3,44,22,0,209,210,5,46,0,0,210,217,1,0,0,0,211,217,5,
		17,0,0,212,214,7,0,0,0,213,212,1,0,0,0,213,214,1,0,0,0,214,215,1,0,0,0,
		215,217,7,1,0,0,216,203,1,0,0,0,216,207,1,0,0,0,216,211,1,0,0,0,216,213,
		1,0,0,0,217,224,1,0,0,0,218,219,10,5,0,0,219,220,3,48,24,0,220,221,3,44,
		22,6,221,223,1,0,0,0,222,218,1,0,0,0,223,226,1,0,0,0,224,222,1,0,0,0,224,
		225,1,0,0,0,225,45,1,0,0,0,226,224,1,0,0,0,227,228,5,41,0,0,228,229,5,
		14,0,0,229,47,1,0,0,0,230,231,7,2,0,0,231,49,1,0,0,0,232,233,5,36,0,0,
		233,51,1,0,0,0,17,56,61,73,75,121,126,132,141,150,161,178,190,193,197,
		213,216,224
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Jacobi.CuplLang.Parser
